In [41]:
from ccdc import io
from ccdc.io import EntryReader

from collections import defaultdict
from itertools import islice

from tqdm import tqdm

import pandas as pd

import time

from concurrent.futures import ProcessPoolExecutor

In [42]:
csd = EntryReader('CSD')
csd_reader = io.EntryReader('CSD')

### 1. Extract all records to single CSV table

In [43]:
all_df = []

start = time.time()

total_entry = 500
for entry in tqdm(islice(csd, total_entry), total=total_entry, desc="Traitement"):

    # check organic
    is_organic = entry.is_organic

    # check num components
    num_component = len(entry.molecule.components)

    # check metal
    has_metal = any(atom.is_metal for atom in entry.molecule.atoms)

    # add result
    all_df.append({
        "ID":entry.identifier,
        "SMILES": entry.molecule.smiles,
        "IS_ORGANIC": is_organic,
        "HAS_METAL":has_metal,
        "NUM_COMPONENT": num_component,
    })

delta_time = round(time.time() - start, 1)

all_df = pd.DataFrame(all_df)
all_df.to_csv("csd_all.csv", index=False)

print(f"Sequential : Processed {len(all_df)//1000}k entries in {delta_time}s")

Traitement: 100%|████████████████████████████| 500/500 [00:02<00:00, 168.93it/s]

Sequential : Processed 0k entries in 3.0s

In [44]:
all_df

,ID,SMILES,IS_ORGANIC,HAS_METAL,NUM_COMPONENT
0,AABHTZ,CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O,True,False,1
1,AACANI10,[OH2][Ni]123OC(=O)CN41CCCN2(CCC4)CC(=O)O3.O.O,False,True,3
2,AACANI11,[OH2][Ni]123OC(=O)CN41CCCN2(CCC4)CC(=O)O3.O.O,False,True,3
3,AACFAZ,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
4,AACFAZ10,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
...,...,...,...,...,...
495,ABAZPT,CC(=O)N1=NC(=[NH][Pt]21[NH]=C(N=N2C(C)=O)C(C)(...,False,True,1
496,ABAZUA,Cc1cc(C)c(c(C)c1)B1(c2ccccc2c2ccc(cn12)c1ccc(c...,True,False,1
497,ABAZUB,O.COc1cc(Nc2c(cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23...,True,False,2
498,ABAZUB01,COc1cc(Nc2c(cnc3cc(OCCCN4CCN(C)CC4)c(OC)cc23)C...,True,False,2
499,ABAZUC,CC(C)(C)N#C[Cu]12O3(C(C)(C)C)[Cu]4(C#NC(C)(C)C...,False,True,1

In [55]:
start = time.time()

def chunk_extraction(chunk_range):
    start, stop = chunk_range
    results = []
    with io.EntryReader('CSD') as reader:
        for i in range(start, stop):
            entry = reader[i]
            mol = entry.molecule
            results.append({
                "ID": entry.identifier,
                "SMILES": mol.smiles,
                "IS_ORGANIC": entry.is_organic,
                "HAS_METAL": any(atom.is_metal for atom in mol.atoms),
                "NUM_COMPONENT": len(mol.components),
            })
    return results

with io.EntryReader('CSD') as reader:
    NUMBER_ENTRIES = len(reader)

# NUMBER_ENTRIES = 50000
NUM_WORKERS = 24
CHUNK_SIZE = 500
chunk_ranges = [(i, min(i + CHUNK_SIZE, NUMBER_ENTRIES)) for i in range(0, NUMBER_ENTRIES, CHUNK_SIZE)]
pbar = tqdm(total=NUMBER_ENTRIES, unit="entry", desc=f"Extraction ({NUM_WORKERS} workers)", smoothing=0.1)

with ProcessPoolExecutor(max_workers=NUM_WORKERS) as executor:
    all_results = []
    for chunk_results in executor.map(chunk_extraction, chunk_ranges):
        all_results.extend(chunk_results)
        pbar.update(len(chunk_results))
pbar.close()

delta_time = round(time.time() - start, 1)

all_df = pd.DataFrame(all_results)
all_df.to_csv("csd_all.csv", index=False)

print(f"Processed {len(all_df)//1000}k entries in {delta_time}s ({NUM_WORKERS} workers)")

Extraction (24 workers): 100%|███| 1436119/1436119 [09:32<00:00, 2508.23entry/s]

Processed 1436k entries in 572.6s (24 workers)

In [28]:
all_df

,ID,SMILES,IS_ORGANIC,HAS_METAL,NUM_COMPONENT
0,AABHTZ,CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O,True,False,1
1,AACANI10,[OH2][Ni]123OC(=O)CN41CCCN2(CCC4)CC(=O)O3.O.O,False,True,3
2,AACANI11,[OH2][Ni]123OC(=O)CN41CCCN2(CCC4)CC(=O)O3.O.O,False,True,3
3,AACFAZ,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
4,AACFAZ10,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
...,...,...,...,...,...
499995,IYUYUY,CCCCCCC1c2cc3C(CCCCCC)c4cc5C(CCCCCC)c6cc7C(CCC...,True,False,6
499996,IYUYUZ,CC1=CNC(=O)NC1=O.O,True,False,2
499997,IYUYUZ01,CC1=CNC(=O)NC1=O.O,True,False,2
499998,IYUYUZ02,CC1=CNC(=O)NC1=O.O,True,False,2
499999,IYUYUZ03,CC1=CNC(=O)NC1=O.O,True,False,2

### 2. Select only organic one component molecules

In [42]:
all_df = pd.read_csv("csd_all.csv")

df_filtered = all_df[
    (all_df["IS_ORGANIC"] == True) &
    (all_df["HAS_METAL"] == False) &
    (all_df["NUM_COMPONENT"] == 1)
]

print(f"Selected {len(df_filtered)} entries")

Selected 1423 entries

In [43]:
df_filtered

,ID,SMILES,IS_ORGANIC,HAS_METAL,NUM_COMPONENT
0,AABHTZ,CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O,True,False,1
3,AACFAZ,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
4,AACFAZ10,COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...,True,False,1
6,AACMHX10,CC(=O)OC(=C1CCCCC1c1ccccc1)c1ccccc1,True,False,1
19,AAMAND,COC1CCC2(C)C(CCC3C2CCC2(C)C3CC2C(C)=O)C1,True,False,1
...,...,...,...,...,...
4978,ACIZES,CC(C)c1cc(C(C)C)c(c(c1)C(C)C)[Si](=P)[Si](C(C)...,True,False,1
4979,ACIZET,FC(F)(F)c1cccc(NC(=S)NC2CCCCC2)c1,True,False,1
4989,ACIZOC,CC(C)[Si]1(O[Si](P[Si](O[Si](P1)(C(C)C)C(C)C)(...,True,False,1
4990,ACIZOD,CC1=NN(c2ccccc2)C2=C1C1(C)C(COc3ccccc13)CO2,True,False,1
4996,ACIZUJ,CCOC=C(C(=O)C#C[Si](C)(C)C)c1ccc(cc1)N(=O)=O,True,False,1

### 3. Count the number of crystal forms

In [44]:
groups = defaultdict(list)
for entry_id in tqdm(df_filtered["ID"]):

    mol = csd_reader.molecule(entry_id)
    key = mol.generate_inchi().inchi

    if key:  # skip if missing
        groups[key].append(mol.identifier)

print(f"Selected {len(groups)} molecules with InChIKey")

100%|██████████████████████████████████████████████████████████████████████████████| 1423/1423 [00:03<00:00, 456.10it/s]

Selected 1192 molecules with InChIKey

In [45]:
df_filtered = df_filtered.set_index("ID")

df_counted = []

for key, entries in groups.items():
    num_forms = len(entries)

    df_counted.append({
        "SMILES": df_filtered.loc[entries[0]]["SMILES"],
        "NUM_FORMS": len(entries)
    })

df_counted = pd.DataFrame(df_counted)
df_counted = df_counted.drop_duplicates("SMILES")

print(f"Selected {len(df_counted)} molecules with counted forms")

Selected 1175 molecules with counted forms

In [46]:
n_total = len(df_counted)
n_mono = sum(df_counted["NUM_FORMS"] == 1)
n_poly = sum(df_counted["NUM_FORMS"] > 1)

print(f"Total molecules: {n_total}")
print(f"Monomorphs: {n_mono} ({round(100 * n_mono / n_total, 1)} %)")
print(f"Polymorphs: {n_poly} ({round(100 * n_poly / n_total, 1)} %)")

Total molecules: 1175
Monomorphs: 1104 (94.0 %)
Polymorphs: 71 (6.0 %)

In [48]:
df_counted.to_csv("csd_counted.csv", index=False)

### 4. Properties

In [72]:
entry = csd[0]
properties = dir(entry)
entry.ccdc_number?
properties

['CrossReference',
 '_CENTIGRADE',
 '_CifAttributes',
 '_KELVIN',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_diagram_is_polymeric',
 '_entry',
 '_experimental_info',
 '_fetch_datum',
 '_hydrogen_treatment_map',
 '_hydrogen_treatment_map_inverse',
 '_make_citation',
 '_make_crystal',
 '_make_diagram',
 '_melting_point_parser',
 '_radiation_source_map',
 '_source_file_availability_map',
 '_source_file_availability_map_inverse',
 'analogue',
 'attributes',
 'bioactivity',
 'calculated_density',
 'calculated_properties',
 'ccdc_number',
 'chemical_name',
 'chemical_name_as_html',
 'color',
 'component_inchis',
 'cross_references',
 'crystal',
 'database_name',
 'deposition_date',
 'disorder_details',
 'disordered_molecule',
 'doi',
 'fcf_source',
 'flack_parameter',
 'formatted_melting_point_range',
 'formatted_melting_point_text',
 'formula',
 'from_molecule',
 'from_string',
 'habit',
 'has_3d_structure',
 'has_disorder',
 'heat_capacity',
 'heat_capacity_notes',
 'heat_of_fusion',
 'heat_of_fusion_notes',
 'hkl_source',
 'hydrogen_treatment',
 'identifier',
 'input_melting_point_range',
 'input_melting_point_text',
 'is_organic',
 'is_organometallic',
 'is_polymeric',
 'is_powder_study',
 'melting_point',
 'melting_point_default_units',
 'melting_point_display_string',
 'molecule',
 'peptide_sequence',
 'phase_transition',
 'polymorph',
 'predicted_properties',
 'pressure',
 'previous_identifier',
 'publication',
 'publications',
 'r_factor',
 'radiation_source',
 'raw_data_dois',
 'refinement_details',
 'refinement_goodness_of_fit',
 'refinement_max_shift',
 'refinement_number_of_constraints',
 'refinement_number_of_parameters',
 'refinement_number_of_restraints',
 'refinement_residual_electron_density_max',
 'refinement_residual_electron_density_min',
 'refinement_weighted_r_factor',
 'reflection_max_theta',
 'remarks',
 'res_source',
 'resolution',
 'solubility_data',
 'solvent',
 'source',
 'synonyms',
 'synonyms_as_html',
 'temperature',
 'to_string',
 'wavelengths']

Type:        property
String form: <property object at 0x7ea3f539ade0>
Docstring:
The CCDC deposition number.

>>> from ccdc.io import EntryReader
>>> entry_reader = EntryReader('CSD')
>>> abebuf = entry_reader.entry('ABEBUF')
>>> print(abebuf.ccdc_number)
241370

In [101]:
BANNED_LIST = ['melting_point_display_string', 'input_melting_point_range', 'formatted_melting_point_text', 'formatted_melting_point_range' ]
MAX_ENTRIES_TEST = 100

prop_list = {}
for prop in dir(entry):
    if prop.startswith('_') or prop in BANNED_LIST:
        continue

    try:
        attr_class = getattr(type(entry), prop, None)
        if isinstance(attr_class, property):
            doc = getattr(attr_class.fget, '__doc__', None)
        else:
            doc = getattr(getattr(entry, prop), '__doc__', None)

        doc_clean = doc.split('>>>')[0].split(':')[0].strip() if doc else None

        example_value = None
        for i, test_entry in enumerate(islice(csd, MAX_ENTRIES_TEST)):
            try:
                value = getattr(test_entry, prop)
                if value:
                    example_value = value
                    break
            except:
                continue

        # if str(example_value)[0] == '<':
        #     continue

        prop_list[prop] = {
            "description": doc_clean,
            "example": str(example_value) if example_value is not None else "No example found"
        }

    except Exception as e:
        if "Solubility Platform" not in str(e):
            print(f"Error with {prop} : {e}")

for prop, infos in prop_list.items():
    if infos['example'][0] == "<":
        print(f"--- {prop} ---")
        print(f"Description : {infos['description']}")
        print(f"Exemple : {infos['example']}")
        print()

print(len(prop_list))

--- CrossReference ---
Description : A cross-reference between entries in the database.
Exemple : <class 'ccdc.entry.Entry.CrossReference'>

--- calculated_properties ---
Description : Returns the calculated properties for the entry, or None if they have not been provided.
Exemple : <ccdc.entry.CrystalCalculatedProperties object at 0x7ea37a522650>

--- crystal ---
Description : The
Exemple : <ccdc.crystal.Crystal object at 0x7ea37a5ede50>

--- disordered_molecule ---
Description : The
Exemple : <ccdc.molecule.Molecule object at 0x7ea37a599d10>

--- from_molecule ---
Description : Construct an entry from a molecule, using the keyword arguments as attributes.
Exemple : <function Entry.from_molecule at 0x7ea3f53a7380>

--- from_string ---
Description : Create an entry from a string representation.

        The format will be auto-detected if not specified.
Exemple : <function Entry.from_string at 0x7ea3f53b00e0>

--- molecule ---
Description : The
Exemple : <ccdc.molecule.Molecule object at 0x7ea37a416490>

--- predicted_properties ---
Description : Returns the predicted properties for the entry, or None if they have not been provided.
Exemple : <ccdc.entry.CrystalPredictedProperties object at 0x7ea37a7cd850>

--- to_string ---
Description : Return a string representation of an entry.
Exemple : <bound method Entry.to_string of <ccdc.entry.Entry object at 0x7ea37a544610>>

73

In [108]:
BANNED_LIST = ['melting_point_display_string', 'input_melting_point_range',
               'formatted_melting_point_text', 'formatted_melting_point_range']
MAX_ENTRIES_TEST = 100

entry = csd[0]
molecule = entry.molecule

prop_list = {}
for prop in dir(molecule):
    if prop.startswith('_') or prop in BANNED_LIST:
        continue

    try:
        attr_class = getattr(type(molecule), prop, None)
        if isinstance(attr_class, property):
            doc = getattr(attr_class.fget, '__doc__', None)
        else:
            doc = getattr(getattr(molecule, prop), '__doc__', None)

        doc_clean = doc.split('>>>')[0].split(':')[0].strip() if doc else None

        example_value = None
        for test_entry in islice(csd, MAX_ENTRIES_TEST):
            try:
                value = getattr(test_entry.molecule, prop)
                if value:
                    example_value = value
                    break
            except:
                continue

        # if str(example_value)[0] == '<':
        #     continue
        
        prop_list[prop] = {
            "description": doc_clean,
            "example": str(example_value) if example_value is not None else "No example found"
        }

    except Exception as e:
        if "Solubility Platform" not in str(e):
            print(f"Error with {prop} : {e}")

for prop, infos in prop_list.items():
    print(f"--- {prop} ---")
    print(f"Description : {infos['description']}")
    print(f"Exemple : {infos['example']}")
    print()

print(len(prop_list))

--- Contact ---
Description : A contact between two molecules.
Exemple : <class 'ccdc.molecule.Molecule.Contact'>

--- HBond ---
Description : A hydrogen bond between atoms of a molecule.
Exemple : <class 'ccdc.molecule.Molecule.HBond'>

--- HBondCriterion ---
Description : Defines the conditions for an HBond to be detected in a molecule.

        Contains two dictionary like objects for the donor atom types and the acceptor atom types,
        whether or not hydrogens are required, a distance range and an angle tolerance
        (if hydrogen atoms are required), whether or not the distance range is relative to Van der Waals radii,
        whether inter-, intra- or both HBonds should be detected, and a range of path separation distances for atoms
        to be considered hydrogen bonded.

        In almost all cases the defaults will give good results, but users may wish to fine-tune the detection algorithm.
Exemple : <class 'ccdc.molecule.Molecule.HBondCriterion'>

--- Transformation ---
Description : Transformation matrix that could be applied to the coordinates of a molecule
Exemple : <class 'ccdc.molecule.Molecule.Transformation'>

--- add_atom ---
Description : Add an atom.
Exemple : <bound method Molecule.add_atom of <ccdc.molecule.Molecule object at 0x7ea37a5fc290>>

--- add_atoms ---
Description : Add atoms, whether from another molecule or constructed *ab initio*.
Exemple : <bound method Molecule.add_atoms of <ccdc.molecule.Molecule object at 0x7ea37a546a90>>

--- add_bond ---
Description : Add a bond between two atoms.
Exemple : <bound method Molecule.add_bond of <ccdc.molecule.Molecule object at 0x7ea37a545f90>>

--- add_bonds ---
Description : Add several bonds to the molecule.
Exemple : <bound method Molecule.add_bonds of <ccdc.molecule.Molecule object at 0x7ea37a417290>>

--- add_group ---
Description : Add a group from another molecule.

        All atoms and bonds of downstream of the pair atom1, atom2 will be added to the molecule.
Exemple : <bound method Molecule.add_group of <ccdc.molecule.Molecule object at 0x7ea37a7d4550>>

--- add_hydrogens ---
Description : Add hydrogen atoms to the molecule.
Exemple : <bound method Molecule.add_hydrogens of <ccdc.molecule.Molecule object at 0x7ea37a575a90>>

--- add_molecule ---
Description : Add a copy of all the atoms and bonds of molecule.
Exemple : <bound method Molecule.add_molecule of <ccdc.molecule.Molecule object at 0x7ea37a517590>>

--- all_atoms_have_sites ---
Description : Whether all atoms have coordinates.
Exemple : True

--- apply_quaternion ---
Description : Apply a Quaternion to the molecule, rotating it about an arbitrary axis.
Exemple : <bound method Molecule.apply_quaternion of <ccdc.molecule.Molecule object at 0x7ea36acc5410>>

--- assign_bond_types ---
Description : Assign bond types to the molecule.
Exemple : <bound method Molecule.assign_bond_types of <ccdc.molecule.Molecule object at 0x7ea37a545a90>>

--- assign_partial_charges ---
Description : Assigns partial charges to atoms using the Gasteiger-Marsili algorithm.

        Reference
Exemple : <bound method Molecule.assign_partial_charges of <ccdc.molecule.Molecule object at 0x7ea37a545010>>

--- atom ---
Description : The unique atom with this label.
Exemple : <bound method Molecule.atom of <ccdc.molecule.Molecule object at 0x7ea37a544a90>>

--- atoms ---
Description : List of the atoms in the molecule.
Exemple : [Atom(Cl1), Atom(Cl2), Atom(C1), Atom(C2), Atom(C3), Atom(C4), Atom(C5), Atom(C6), Atom(C7), Atom(N1), Atom(N2), Atom(C8), Atom(N3), Atom(N4), Atom(C9), Atom(N5), Atom(N6), Atom(C10), Atom(C11), Atom(O1), Atom(C12), Atom(C13), Atom(O2), Atom(H1), Atom(H2), Atom(H3), Atom(H4), Atom(H5), Atom(H6), Atom(H7), Atom(H8), Atom(H9), Atom(H10), Atom(H11), Atom(H12)]

--- bond ---
Description : The bond between the atoms uniquely so labelled.
Exemple : <bound method Molecule.bond of <ccdc.molecule.Molecule object at 0x7ea37a87da90>>

--- bonds ---
Description : List of the bonds in the molecule.
Exemple : [Bond(Single Atom(Cl1) Atom(C1)), Bond(Single Atom(Cl2) Atom(C5)), Bond(Aromatic Atom(C1) Atom(C2)), Bond(Aromatic Atom(C1) Atom(C6)), Bond(Aromatic Atom(C2) Atom(C3)), Bond(Single Atom(C2) Atom(H1)), Bond(Aromatic Atom(C3) Atom(C4)), Bond(Single Atom(C3) Atom(H2)), Bond(Aromatic Atom(C4) Atom(C5)), Bond(Single Atom(C4) Atom(H3)), Bond(Aromatic Atom(C5) Atom(C6)), Bond(Single Atom(C6) Atom(C7)), Bond(Double Atom(C7) Atom(N1)), Bond(Single Atom(C7) Atom(H4)), Bond(Single Atom(N1) Atom(N2)), Bond(Single Atom(N2) Atom(C8)), Bond(Single Atom(N2) Atom(C12)), Bond(Double Atom(C8) Atom(N3)), Bond(Single Atom(C8) Atom(N5)), Bond(Single Atom(N3) Atom(N4)), Bond(Double Atom(N4) Atom(C9)), Bond(Single Atom(C9) Atom(N5)), Bond(Single Atom(C9) Atom(H5)), Bond(Single Atom(N5) Atom(N6)), Bond(Single Atom(N6) Atom(C10)), Bond(Single Atom(N6) Atom(H6)), Bond(Single Atom(C10) Atom(C11)), Bond(Double Atom(C10) Atom(O1)), Bond(Single Atom(C11) Atom(H7)), Bond(Single Atom(C11) Atom(H8)), Bond(Single Atom(C11) Atom(H9)), Bond(Single Atom(C12) Atom(C13)), Bond(Double Atom(C12) Atom(O2)), Bond(Single Atom(C13) Atom(H10)), Bond(Single Atom(C13) Atom(H11)), Bond(Single Atom(C13) Atom(H12))]

--- centre_of_geometry ---
Description : Geometric centre of the molecule.
Exemple : <bound method Molecule.centre_of_geometry of <ccdc.molecule.Molecule object at 0x7ea37a7b5110>>

--- change_group ---
Description : Transfer a copy of a group of atoms and bonds.

        All atoms downstream of atom1 - atom2 will be removed and copies of all atoms and bonds
        downstream of atom3 - atom4 will be added to the molecule.  The geometry of the copied atoms
        will be translated and rotated such that the bond atom3 - atom4 is aligned with atom1 - atom2.

        The bond connecting the groups will have the same type as that between atom1 and atom2.
Exemple : <bound method Molecule.change_group of <ccdc.molecule.Molecule object at 0x7ea37a544c90>>

--- components ---
Description : List of the disconnected molecules with the molecule.
Exemple : [<ccdc.molecule.Molecule object at 0x7ea37a7de050>]

--- contacts ---
Description : The collection of short nonbonded contacts in this molecule.

        Distance limits for nonbonded contacts are defined as distances relative to the sum
        of van der Waals Radii, *i.e.*
Exemple : <bound method Molecule.contacts of <ccdc.molecule.Molecule object at 0x7ea37a5efcd0>>

--- contains_unknown_bonds ---
Description : Whether the molecule contains unknown bonds.
Exemple : True

--- copy ---
Description : Return a deep copy of the molecule.
Exemple : <bound method Molecule.copy of <ccdc.molecule.Molecule object at 0x7ea37a5dbf10>>

--- formal_charge ---
Description : The formal charge of the molecule represented as an integer.
Exemple : 7

--- formula ---
Description : Return the chemical formula of the molecule.
Exemple : C13 H12 Cl2 N6 O2

--- from_string ---
Description : Create a molecule from a string representation.

        The format will be auto-detected if not specified.
Exemple : <function Molecule.from_string at 0x7ea3fbfa8d60>

--- fuse_rings ---
Description : Fuse a copy of a ring system.

        The bond between atom3 and atom4 will be superimposed on the bond between atom1 and atom2.
Exemple : <bound method Molecule.fuse_rings of <ccdc.molecule.Molecule object at 0x7ea37a599190>>

--- generate_inchi ---
Description : Return a
Exemple : <bound method Molecule.generate_inchi of <ccdc.molecule.Molecule object at 0x7ea37a6d1990>>

--- has_charged_atoms ---
Description : Does molecule contain charged atoms.
Exemple : True

--- hbonds ---
Description : The collection of molecular hydrogen bonds in this molecule.

        The definition of a hydrogen bond (*D-H...A*) is a contact meeting the following criteria
Exemple : <bound method Molecule.hbonds of <ccdc.molecule.Molecule object at 0x7ea37a6d2590>>

--- heaviest_component ---
Description : The heaviest component, useful for stripping solvents.
Exemple : <ccdc.molecule.Molecule object at 0x7ea37a6c60d0>

--- heavy_atoms ---
Description : List of the heavy atoms in the molecule.
Exemple : [Atom(Cl1), Atom(Cl2), Atom(C1), Atom(C2), Atom(C3), Atom(C4), Atom(C5), Atom(C6), Atom(C7), Atom(N1), Atom(N2), Atom(C8), Atom(N3), Atom(N4), Atom(C9), Atom(N5), Atom(N6), Atom(C10), Atom(C11), Atom(O1), Atom(C12), Atom(C13), Atom(O2)]

--- identifier ---
Description : The string identifier of the molecule, e.g. 'ABEBUF'.
Exemple : AABHTZ

--- is_3d ---
Description : Whether the molecule has 3d coordinates for all heavy atoms.
Exemple : True

--- is_organic ---
Description : Uses CSD definitions for organometallic molecules.
Exemple : True

--- is_organometallic ---
Description : Uses CSD definitions for organometallic molecules.
Exemple : True

--- is_polymeric ---
Description : Whether the molecule contains polymeric bonds.
Exemple : True

--- kekulize ---
Description : Convert the molecule to a Kekule representation, replacing all aromatic bonds by alternating single
        and double bonds.
Exemple : <bound method Molecule.kekulize of <ccdc.molecule.Molecule object at 0x7ea37a598f10>>

--- largest_ring_size ---
Description : The size of the largest basic
Exemple : 6

--- molecular_volume ---
Description : The molecular volume of the molecule.
Exemple : 287.8008594614636

--- molecular_weight ---
Description : The molecular weight of the molecule.
Exemple : 355.1788999999999

--- normalise_atom_order ---
Description : Reorder the atoms of the molecule canonically.

        This will not work for structures with unknown atoms or bonds.

        This may be useful for comparing polymorphs, for example
Exemple : <bound method Molecule.normalise_atom_order of <ccdc.molecule.Molecule object at 0x7ea37a417690>>

--- normalise_hydrogens ---
Description : Normalise the hydrogen atom positions in the molecule.

        This will normalise the position of hydrogen atoms attached to oxygen,
        nitrogen or carbon atoms to standard X-H distance values derived from
        statistical surveys of neutron diffraction data.

        Note that this function will only modify the X-H distance. In other
        words the bond vector direction will be unaffected.
Exemple : <bound method Molecule.normalise_hydrogens of <ccdc.molecule.Molecule object at 0x7ea37a40a390>>

--- normalise_labels ---
Description : Ensure labels of atoms are unique.

        Labels will be the atom's atomic symbol followed by an integer.
Exemple : <bound method Molecule.normalise_labels of <ccdc.molecule.Molecule object at 0x7ea37a6d2f10>>

--- remove_atom ---
Description : Remove an atom from the molecule.
Exemple : <bound method Molecule.remove_atom of <ccdc.molecule.Molecule object at 0x7ea37a5ecdd0>>

--- remove_atoms ---
Description : Remove several atoms from the molecule.
Exemple : <bound method Molecule.remove_atoms of <ccdc.molecule.Molecule object at 0x7ea37a59a590>>

--- remove_bond ---
Description : Remove a bond.
Exemple : <bound method Molecule.remove_bond of <ccdc.molecule.Molecule object at 0x7ea37a7a70d0>>

--- remove_bonds ---
Description : Remove bonds.
Exemple : <bound method Molecule.remove_bonds of <ccdc.molecule.Molecule object at 0x7ea37a5efa50>>

--- remove_group ---
Description : Remove the group of atoms and bonds downstream from atom1, atom2.
Exemple : <bound method Molecule.remove_group of <ccdc.molecule.Molecule object at 0x7ea37a577090>>

--- remove_hydrogens ---
Description : Remove all hydrogen atoms.
Exemple : <bound method Molecule.remove_hydrogens of <ccdc.molecule.Molecule object at 0x7ea37a59b710>>

--- remove_partial_charges ---
Description : Removes partial charges from all atoms.
Exemple : <bound method Molecule.remove_partial_charges of <ccdc.molecule.Molecule object at 0x7ea37a5eef50>>

--- remove_unknown_atoms ---
Description : Remove all atoms with an atomic number of zero (e.g. lone pairs, dummy atoms).
Exemple : <bound method Molecule.remove_unknown_atoms of <ccdc.molecule.Molecule object at 0x7ea37a599990>>

--- rings ---
Description : The collection of basic
Exemple : [Atom(C5)-Atom(C6)-Atom(C1)-Atom(C2)-Atom(C3)-Atom(C4), Atom(C9)-Atom(N5)-Atom(C8)-Atom(N3)-Atom(N4)]

--- rotate ---
Description : Rotate a molecule about the vector xyz by theta degrees.

        The molecule will be rotated about its centre of geometry.
Exemple : <bound method Molecule.rotate of <ccdc.molecule.Molecule object at 0x7ea37a87db10>>

--- set_bond_length ---
Description : Set the bond length between the two atoms to distance.
Exemple : <bound method Molecule.set_bond_length of <ccdc.molecule.Molecule object at 0x7ea37a6d0490>>

--- set_coordinates ---
Description : Set the coordinates of this molecule to those of the other molecule.

        For example AACFAZ has no coordinates, so in some circumstances one might wish to use the coordinates from AACFAZ10.
Exemple : <bound method Molecule.set_coordinates of <ccdc.molecule.Molecule object at 0x7ea37a5ef750>>

--- set_formal_charges ---
Description : Calculate formal charges for atoms assuming bond types and protonation are correct.
Exemple : <bound method Molecule.set_formal_charges of <ccdc.molecule.Molecule object at 0x7ea37a514cd0>>

--- set_residue_by_component ---
Description : Sets the residue label of disconnected components of the molecule.
Exemple : <bound method Molecule.set_residue_by_component of <ccdc.molecule.Molecule object at 0x7ea37a7447d0>>

--- set_torsion_angle ---
Description : Set the torsion angle between the specified atoms to theta.
Exemple : <bound method Molecule.set_torsion_angle of <ccdc.molecule.Molecule object at 0x7ea37a7a6fd0>>

--- set_valence_angle ---
Description : Set the valence angle subtended by atom1, atom2, atom3 to theta.
Exemple : <bound method Molecule.set_valence_angle of <ccdc.molecule.Molecule object at 0x7ea37a5ef950>>

--- shortest_path ---
Description : Return the shortest path between two atoms.
Exemple : <bound method Molecule.shortest_path of <ccdc.molecule.Molecule object at 0x7ea37a5fe5d0>>

--- shortest_path_atoms ---
Description : The list of atoms along the shortest path from atom1 to atom2.
Exemple : <bound method Molecule.shortest_path_atoms of <ccdc.molecule.Molecule object at 0x7ea37a5ef750>>

--- shortest_path_bonds ---
Description : The list of bonds along the shortest path from atom1 to atom2.
Exemple : <bound method Molecule.shortest_path_bonds of <ccdc.molecule.Molecule object at 0x7ea37a7a6fd0>>

--- smallest_ring_size ---
Description : Size of the smallest
Exemple : 5

--- smiles ---
Description : The canonical SMILES representation of the molecule.

        This will raise a RuntimeError if the molecule contains unknown atoms
        or bonds, delocalised bonds or if there are non-terminal hydrogens.
Exemple : CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O

--- standardise_aromatic_bonds ---
Description : Standardise aromatic bonds to CSD conventions.
Exemple : <bound method Molecule.standardise_aromatic_bonds of <ccdc.molecule.Molecule object at 0x7ea37a746350>>

--- standardise_delocalised_bonds ---
Description : Standardise delocalised bonds to CSD conventions.
Exemple : <bound method Molecule.standardise_delocalised_bonds of <ccdc.molecule.Molecule object at 0x7ea37a429b90>>

--- to_string ---
Description : Return a string representation of a molecule.
Exemple : <bound method Molecule.to_string of <ccdc.molecule.Molecule object at 0x7ea37a87f010>>

--- transform ---
Description : Apply a matrix to the coordinates of the molecule.

        The method will not check that the matrix is appropriate for a molecular
        transformation; it is for the user to ensure that inappropriate affine
        transformations are avoided.
Exemple : <bound method Molecule.transform of <ccdc.molecule.Molecule object at 0x7ea37a744dd0>>

--- translate ---
Description : Translate the molecule.
Exemple : <bound method Molecule.translate of <ccdc.molecule.Molecule object at 0x7ea37a6de750>>

72