In [1]:
import numpy as np
import pandas as pd

from rdkit import Chem

from tqdm import tqdm

In [2]:
def safe_mol(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles, sanitize=False)
        if mol is None:
            return None

        Chem.SanitizeMol(mol)  # this is where valence/kekulization errors appear
        return mol
    except:
        return None

In [4]:
df_counted = pd.read_csv("csd_counted.csv")
df_counted

                                                 SMILES  NUM_FORMS
0            CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O          1
1     COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...          1
2                   CC(=O)OC(=C1CCCCC1c1ccccc1)c1ccccc1          1
3                 CC1CC(C)OP(=S)(O1)OP1(=S)OC(C)CC(C)O1          1
4                                CC(=O)C=C(C)Nc1cncnc1N          1
...                                                 ...        ...
1170  CC(C)c1cc(C(C)C)c(c(c1)C(C)C)[Si](=P)[Si](C(C)...          1
1171                  FC(F)(F)c1cccc(NC(=S)NC2CCCCC2)c1          1
1172  CC(C)[Si]1(O[Si](P[Si](O[Si](P1)(C(C)C)C(C)C)(...          1
1173        CC1=NN(c2ccccc2)C2=C1C1(C)C(COc3ccccc13)CO2          1
1174       CCOC=C(C(=O)C#C[Si](C)(C)C)c1ccc(cc1)N(=O)=O          1

[1175 rows x 2 columns]

In [13]:
valid_rows = []
for idx, smi in df_counted["SMILES"].items():
    
    if smi is np.nan:
        continue
    
    mol = safe_mol(smi)
    if mol:
        valid_rows.append(idx)

df_cleaned = df_counted.loc[valid_rows].copy()

[14:40:36] Explicit valence for atom # 8 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 29 Cl, 2, is greater than permitted
[14:40:36] Explicit valence for atom # 9 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 1 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 2 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 8 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 6 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 7 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 6 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 11 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 6 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 11 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 10 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 7 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 7 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 8 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 1 B, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 1 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 9 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 15 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 1 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 1 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 17 B, 5, is greater than permitted
[14:40:36] Explicit valence for atom # 13 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 13 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 2 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 14 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 11 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 0 B, 4, is greater than permitted
[14:40:36] Can't kekulize mol.  Unkekulized atoms: 7 9 10 11 12 13 14 15 17
[14:40:36] Explicit valence for atom # 8 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 26 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 1 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 26 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 10 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 0 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 25 C, 6, is greater than permitted
[14:40:36] Explicit valence for atom # 9 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 6 B, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 4 N, 4, is greater than permitted
[14:40:36] Explicit valence for atom # 0 H, 2, is greater than permitted
[14:40:36] Explicit valence for atom # 31 Si, 5, is greater than permitted

In [14]:
df_cleaned

                                                 SMILES  NUM_FORMS
0            CC(=O)NN1C=NN=C1N(N=Cc1c(Cl)cccc1Cl)C(C)=O          1
1     COC1=C(C(OC1=O)c1ccccc1Cl)C(C)=NN=C(C)C1=C(OC)...          1
2                   CC(=O)OC(=C1CCCCC1c1ccccc1)c1ccccc1          1
3                 CC1CC(C)OP(=S)(O1)OP1(=S)OC(C)CC(C)O1          1
4                                CC(=O)C=C(C)Nc1cncnc1N          1
...                                                 ...        ...
1170  CC(C)c1cc(C(C)C)c(c(c1)C(C)C)[Si](=P)[Si](C(C)...          1
1171                  FC(F)(F)c1cccc(NC(=S)NC2CCCCC2)c1          1
1172  CC(C)[Si]1(O[Si](P[Si](O[Si](P1)(C(C)C)C(C)C)(...          1
1173        CC1=NN(c2ccccc2)C2=C1C1(C)C(COc3ccccc13)CO2          1
1174       CCOC=C(C(=O)C#C[Si](C)(C)C)c1ccc(cc1)N(=O)=O          1

[1124 rows x 2 columns]

In [16]:
df_cleaned.to_csv("csd_cleaned.csv", index=False)