In [7]:
import numpy as np
import pandas as pd

from rdkit import Chem

from tqdm import tqdm

In [8]:
def safe_mol(smiles):
    try:
        mol = Chem.MolFromSmiles(smiles, sanitize=False)
        if mol is None:
            return None

        Chem.SanitizeMol(mol)  # this is where valence/kekulization errors appear
        return mol
    except:
        return None

In [9]:
df_counted = pd.read_csv("csd_counted.csv")
df_counted

,identifier,chemical_name,is_racemic_name,is_organic,has_metal,num_components,is_single_species,has_disorder,disorder_details,color,...,cell_angle_beta,cell_angle_gamma,cell_volume,reduced_cell_a,reduced_cell_b,reduced_cell_c,reduced_cell_alpha,reduced_cell_beta,reduced_cell_gamma,num_forms
0,AABHTZ,"4-Acetoamido-3-(1-acetyl-2-(2,6-dichlorobenzyl...",False,True,False,1,True,False,NaN,NaN,...,71.070,96.160,769.978363,7.3590,10.2720,11.365707,84.217121,71.162715,71.250,1
1,AACFAZ10,"N,N'-bis(3-Acetyl-4-(2-chlorophenyl)-4-hydroxy...",False,True,False,1,True,False,NaN,red,...,90.000,90.000,2475.361224,6.1620,19.9540,20.132000,90.000000,90.000000,90.000,1
2,AACMHX10,"α-Acetoxy-α,2-anti-diphenylmethylene-cyclohexane",False,True,False,1,True,False,NaN,NaN,...,90.000,90.000,3455.164356,8.5350,16.7580,24.157000,90.000000,90.000000,90.000,1
3,AADRIB,"1,2,3,4-Tetra-O-acetyl-α-D-ribopyranose",False,True,False,2,True,False,NaN,NaN,...,109.180,90.000,1591.259021,8.5900,11.4530,16.443713,90.000000,100.383702,90.000,1
4,AAMTXP,"(a,a)-bis(4,6-Dimethyl-2-thioxo-1,3,2-dioxapho...",False,True,False,1,True,False,NaN,NaN,...,113.380,90.000,1673.976496,9.8870,12.3250,14.966000,113.380000,90.000000,90.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343239,ZUVJOS01,"tris(2,4,6-tribromophenyl)methyl radical",False,True,False,1,True,False,NaN,red,...,100.904,90.000,2359.166565,8.4619,14.4325,19.672600,90.000000,100.904000,90.000,3
343240,ZUYBOM01,"2-(4-chlorophenyl)-1,3-benzothiazole",False,True,False,1,True,False,NaN,colorless,...,98.556,90.000,1101.366516,7.1466,11.0497,14.104000,90.000000,90.000000,98.556,2
343241,ZZZEIG05,triphenylarsane,False,True,False,4,True,False,NaN,whiteish colorless,...,80.072,86.361,2999.830947,11.2004,15.2918,17.882400,84.551000,80.072000,86.361,5
343242,ZZZOLM02,docosanoic acid,False,True,False,1,True,False,NaN,colorless,...,90.052,90.000,2089.560807,5.5210,7.1540,52.904000,90.000000,90.052000,90.000,2
343243,ZZZOYC05,picene,False,True,False,1,True,False,NaN,colorless,...,90.029,90.000,684.742498,6.0613,8.4011,13.447000,90.029000,90.000000,90.000,5

In [10]:
valid_rows = []
for idx, smi in df_counted["smiles"].items():
    
    if smi is np.nan:
        continue
    
    mol = safe_mol(smi)
    if mol:
        valid_rows.append(idx)

df_cleaned = df_counted.loc[valid_rows].copy()

[12:10:02] Explicit valence for atom # 8 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 11 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 13 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 1 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 26 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 10 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7
[12:10:02] Explicit valence for atom # 0 H, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 13 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 11 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 13 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 42 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 P, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 Cl, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 12 As, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 As, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 H, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 3 N, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 25 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 20 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 31 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 26 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 21 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Can't kekulize mol.  Unkekulized atoms: 10 12 14
[12:10:02] Explicit valence for atom # 17 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 10 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 10 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 18 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 1 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 13 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 10 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 10 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 10 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 8 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 2 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 35 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 Si, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 Si, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Can't kekulize mol.  Unkekulized atoms: 10 11 12 13 15
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 5 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 25 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 17 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 22 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 18 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 5 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 14 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 H, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 Cl, 1, is greater than permitted
[12:10:02] Explicit valence for atom # 9 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 14 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 Si, 5, is greater than permitted
[12:10:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 13 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 16 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 7 Si, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 14 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 10 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 9 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 0 H, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 11 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 26 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 10 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 14 C, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 5 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 14 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 7 As, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[12:10:02] Explicit valence for atom # 1 B, 6, is greater than permitted
[12:10:02] Explicit valence for atom # 12 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 4 O, 2, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[12:10:02] Explicit valence for atom # 0 B, 4, is greater than permitted

In [11]:
df_cleaned

,identifier,chemical_name,is_racemic_name,is_organic,has_metal,num_components,is_single_species,has_disorder,disorder_details,color,...,cell_angle_beta,cell_angle_gamma,cell_volume,reduced_cell_a,reduced_cell_b,reduced_cell_c,reduced_cell_alpha,reduced_cell_beta,reduced_cell_gamma,num_forms
0,AABHTZ,"4-Acetoamido-3-(1-acetyl-2-(2,6-dichlorobenzyl...",False,True,False,1,True,False,NaN,NaN,...,71.070,96.160,769.978363,7.3590,10.2720,11.365707,84.217121,71.162715,71.250,1
1,AACFAZ10,"N,N'-bis(3-Acetyl-4-(2-chlorophenyl)-4-hydroxy...",False,True,False,1,True,False,NaN,red,...,90.000,90.000,2475.361224,6.1620,19.9540,20.132000,90.000000,90.000000,90.000,1
2,AACMHX10,"α-Acetoxy-α,2-anti-diphenylmethylene-cyclohexane",False,True,False,1,True,False,NaN,NaN,...,90.000,90.000,3455.164356,8.5350,16.7580,24.157000,90.000000,90.000000,90.000,1
3,AADRIB,"1,2,3,4-Tetra-O-acetyl-α-D-ribopyranose",False,True,False,2,True,False,NaN,NaN,...,109.180,90.000,1591.259021,8.5900,11.4530,16.443713,90.000000,100.383702,90.000,1
4,AAMTXP,"(a,a)-bis(4,6-Dimethyl-2-thioxo-1,3,2-dioxapho...",False,True,False,1,True,False,NaN,NaN,...,113.380,90.000,1673.976496,9.8870,12.3250,14.966000,113.380000,90.000000,90.000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343239,ZUVJOS01,"tris(2,4,6-tribromophenyl)methyl radical",False,True,False,1,True,False,NaN,red,...,100.904,90.000,2359.166565,8.4619,14.4325,19.672600,90.000000,100.904000,90.000,3
343240,ZUYBOM01,"2-(4-chlorophenyl)-1,3-benzothiazole",False,True,False,1,True,False,NaN,colorless,...,98.556,90.000,1101.366516,7.1466,11.0497,14.104000,90.000000,90.000000,98.556,2
343241,ZZZEIG05,triphenylarsane,False,True,False,4,True,False,NaN,whiteish colorless,...,80.072,86.361,2999.830947,11.2004,15.2918,17.882400,84.551000,80.072000,86.361,5
343242,ZZZOLM02,docosanoic acid,False,True,False,1,True,False,NaN,colorless,...,90.052,90.000,2089.560807,5.5210,7.1540,52.904000,90.000000,90.052000,90.000,2
343243,ZZZOYC05,picene,False,True,False,1,True,False,NaN,colorless,...,90.029,90.000,684.742498,6.0613,8.4011,13.447000,90.029000,90.000000,90.000,5

In [12]:
df_cleaned.to_csv("csd_cleaned.csv", index=False)